### ISSUE TITLE
Former MPs

### ISSUE THREAD

**Issue by langsamu** [ukparliament/parliament.uk-things#195]
[Anecdotal criticism](https://twitter.com/cgutteridge/status/976731360873328640) regarding the rendering of [former MPs on the constituency detail page](https://github.com/ukparliament/parliament.uk-things/blob/development/app/views/constituencies/_former_seat_incumbencies.html.haml):
> Labels again, https://beta.parliament.uk/constituencies/TzJ2HjVS … says same person is current and former MP. Correct data, confusing rendering :)

Makes a good point in my opinion.

[I recommended grouping by person](https://twitter.com/langsamu/status/976787796563320832) as a possible improvement.

**Comment by fantasticlife** [comment]
fwiw i don't think i agree. the labelling is confusing but the fact the same person (or different people) were incumbent in that seat for distinct periods is important. the incumbency is a result of votes, is a result of an election. imo we should keep it as a list of representations and, when we finally have election data, intersperse the incumbency data with the election result data. parliament periods and elections define the cadence of democracy. we should be exposing that
same argument for splitting timelines of members over parliament periods and not some arbitrary 10 year span. the person stopped being shadow x secretary and started being minister for x because there was a vote because there was an election

**Comment by langsamu** [comment]
Understood, items are Parliamentary incumbencies (representations).
Labelling then.

Another option:
- 7 May 2015 to 3 May 2017: [Dr Alan Whitehead](https://beta.parliament.uk/people/WQfVXkMX)
- 6 May 2010 to 30 Mar 2015: [Dr Alan Whitehead](https://beta.parliament.uk/people/WQfVXkMX)

Or:
- 7 May 2015 to 3 May 2017
[Dr Alan Whitehead](https://beta.parliament.uk/people/WQfVXkMX)
- 6 May 2010 to 30 Mar 2015
[Dr Alan Whitehead](https://beta.parliament.uk/people/WQfVXkMX)
